---
title: "BSDS Capstone"
author: "Ryan C. Duggan"
date: "June 24 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
options(qwraps2_markup = "markdown") 


library('tidyverse')
library('qwraps2')
library('survival')
library('tree')
library('rpart')
library('randomForest')
library('caret')
library('rpart.plot')
library('ROCR')
library('pROC')
library('missForest')

scaff_pvnot <- function(pvalue) {
  if(pvalue < 0.001) p_txt <- "<0.001"
  else if(pvalue < 0.01) p_txt <- format(pvalue, digits = 1)
  else p_txt <- format(pvalue, digits = 2)
  return(p_txt)
}
```

```{r}
ctscan <- read.csv(file = "../data/CTScan_20190529.csv", 
                   na.strings = c("NA", "NaN", "-888"))
dhr <- read.csv(file = "../data/DHR_20190529.csv", 
                na.strings = c("-888"))
outcomes <- read.csv(file = "../data/Outcome_20190529.csv",  
                     na.strings = c("-888"))
patients <- read.csv(file = "../data/PatientData_20190529.csv", 
                     na.strings = c("NA", "NaN", "-888"))
prehosp <- read.csv(file = "../data/PreHospital_20190529.csv",  
                    na.strings = c("-888"))
```

```{r message=FALSE, warning=FALSE}
#converting DOB and DOT to dates, patient characteristics to factors
patients2 <- patients %>%
  filter(PID != "BKBU-48F36I" & PID != "HJOE-883743") %>% #removing patients w/ birth, injury dates                                                        of 1900/1 - data likely incorrect or innacurate
  mutate_at(vars(PID, PDOB, PDOT, PSEX, PRACE, PETHNIC, PWEIGHTS, PMECH, PSEATB, 
                 PHELMET, PTTRAUMA), as.character) %>%
  mutate_at(vars(PSEX, PRACE, PETHNIC, PMECH, PSEATB, PHELMET), 
            as.factor) %>%
  mutate(PDOB = as.Date(PDOB, format = "%m/%d/%Y", origin = "1900-01-01"), 
         PDOT = as.Date(PDOT, format = "%m/%d/%Y", origin = "1900-01-01"), 
         trauma_time = 
           case_when(nchar(PTTRAUMA) == 1  ~ paste("000", PTTRAUMA, sep = ""),
                     nchar(PTTRAUMA) == 2  ~ paste("00", PTTRAUMA, sep = ""),
                     nchar(PTTRAUMA) == 3  ~ paste("0", PTTRAUMA, sep = ""),
                     nchar(PTTRAUMA) == 4  ~ PTTRAUMA,
                     TRUE                  ~ NA_character_)) %>%
  mutate(trauma_time = as.POSIXct(paste(PDOT, trauma_time), 
                                  format = "%Y-%m-%d %H%M", 
                                  origin = "1900-01-01"),
         inj_mech = case_when(PMECH %in% c(1, 2, 3, 4)       ~ "MVA/Bike", 
                              PMECH %in% c(5,6)              ~ "Fall",
                              PMECH == 7                     ~ "Assault/BFT",
                              PMECH %in% c(0, 8, 9, 10)      ~ "All Other",
                              TRUE                           ~ NA_character_) %>%
           as.factor,
         inj_mech = fct_relevel(inj_mech, "MVA/Bike", "Assault/BFT", "Fall", 
                                "All Other")
         )
  
#Convering lb weights to kg
patients2$PWEIGHT[patients2$PWEIGHTS == 2] <- as.integer(patients2$PWEIGHT * 0.453592)

#Note: in commented-out version of inj_mech, only 4 obs in gunshot, 5 in "other, 1 in sports_misc - collapsing into "all other" for the sake of simplicity, although this would probably not make sense - grouping gunshots with sports-related, etc.
#If filtering to ACGSTOT1 <=8, 4 for gunshot, 8 in other, 0 in sports related

#PMECH, PSEATB, PHELMET contains missing values stored as -888 - added to NA strings in intial import
#patients %>% filter_all(any_vars(. == -888))
```

```{r}
#Creating variables for analysis- indicators of hypotension, hypoxia, and pupil dilation in ED
#arrival_date and arrival_time 

prehosp2 <- prehosp %>%
  mutate_at(vars(PID, EDPAA, APASYM1, ADMODE, ADTYPE, ATRANS, APBILAT, APASYM, 
                 AFLUID), as.character) %>%
  mutate_at(vars(ACEI, EDPAA, EDAAM, APASYM1, ADMODE, ADTYPE, ATRANS, APBILAT, 
                 APASYM, AFLUID, EDFLUID),
            as.factor) %>% 
  filter(EDSAO2 >= 40.1) %>% #99.5th percentile of EDSAO2 = 40.1, - lower values may be errors
  mutate(hypotension_ed = case_when(ALRSBP >= 90    ~ "No",
                                    ALRSBP < 90     ~ "Yes",
                                    TRUE            ~ NA_character_) %>% 
           as.factor,
         hypoxia_ed = case_when(EDSAO2 >= 90    ~ "No", #measured in %, not mmHG
                                EDSAO2 < 90     ~ "Yes",
                                TRUE            ~ NA_character_) %>% as.factor,
         hypotension_prehosp = case_when(LRSBP >= 90 ~ "No",
                                         LRSBP < 90  ~ "Yes",
                                         TRUE        ~ NA_character_) %>%
           as.factor(),
         hypoxia_prehosp = case_when(ASAO2 >= 90 ~ "No",
                                     ASAO2 < 90  ~ "Yes",
                                     TRUE        ~ NA_character_) %>%
           as.factor(),
         pupil_prehosp = case_when(APASYM == "1" | APBILAT == "1" ~ "0",
                                   APASYM == "2" & APBILAT == "2" ~ "1",
                                   TRUE ~ NA_character_) %>% 
           as.factor(),
         pupil_prehosp2 = factor(case_when(APASYM == "1" & APBILAT == "1" ~ "BFDP and Asymmetry",
                                           APASYM == "2" & APBILAT == "1" ~ "BFDP Only",
                                           APASYM == "1" & APBILAT == "2" ~ "Asymmetry Only",
                                           APASYM == "2" & APBILAT == "2" ~ "None")),
         pupil_ed = case_when(APASYM1 == "1" | EDPAA == "1" ~ "0",
                              APASYM1 == "2" & EDPAA == "2" ~ "1",
                              TRUE                          ~ NA_character_) %>% 
           as.factor,
         pupil_ed2 = factor(case_when(APASYM1 == "1" & EDPAA == "1" ~ "BFDP and Asymmetry",
                                      APASYM1 == "2" & EDPAA == "1" ~ "BFDP Only",
                                      APASYM1 == "1" & EDPAA == "2" ~ "Asymmetry Only",
                                      APASYM1 == "2" & EDPAA == "2" ~ "None")),
         arrival_date = as.Date(ADOA, format = "%m/%d/%Y"), 
         ATOA = as.character(ATOA),
         arrival_time = case_when(nchar(ATOA) == 1  ~ paste("000", ATOA, 
                                                            sep = ""),
                                  nchar(ATOA) == 2  ~ paste("00", ATOA, sep = ""),
                                  nchar(ATOA) == 3  ~ paste("0", ATOA, sep = ""),
                                  nchar(ATOA) == 4  ~ ATOA,
                                  TRUE              ~ NA_character_),
         arrival_time = as.POSIXct(paste(ADOA, arrival_time), 
                                   format = "%m/%d/%Y %H%M"))

#Cleaning outcome data - as of 6/14/19 only to reformat PID as a character vector and OCOND (pt outcome) as a factor

outcomes2 <- outcomes %>%
  mutate(PID = as.character(PID), 
         outcome = factor(outcomes$OCOND, labels = c("Alive", "Dead")), 
         followup_date = as.Date(ODATE, format = "%m/%d/%Y"))

# cleaning ctscan data

ctbc_factor_levels <- c("Open", "Partially Open", "Closed")
ct_midline_lvls <- c("No Shift", "< 0.5 cm", "0.5-1.5 cm", "> 1.5 cm")
ctscan_YN_levels <- c("Yes", "No")

ctscan2 <- ctscan %>%
  mutate(PID = as.character(PID),
         ct_date = as.Date(CDOCTS, format = "%m/%d/%Y"), 
         CTOCTS = as.character(CTOCTS), CTBC = as.character(CTBC),
         ct_time = case_when(nchar(CTOCTS) == 1  ~ paste("000", CTOCTS, sep = ""),
                             nchar(CTOCTS) == 2  ~ paste("00", CTOCTS, sep = ""),
                             nchar(CTOCTS) == 3  ~ paste("0", CTOCTS, sep = ""),
                             nchar(CTOCTS) == 4  ~ CTOCTS,
                             TRUE                ~ NA_character_),
         ct_date_time = as.POSIXct(paste(ct_date, ct_time), 
                                   format = "%Y-%m-%d %H%M"),
         #Need to figure out which variables are important to determine abnormal CT - using criteria below leaves 8 normal, 306 abnormal, 2 NA
         #According to https://www.ncbi.nlm.nih.gov/pubmed/20597653, partially open cisterns are associated with positive outcomes - may be abnormal, but should it be grouped with more negative closed cisterns?
         #Same paper also associates midline shifts of > 1.5 w/ unfavorable outcomes - but depends on whether we are defining as abnormal by unfavorable levels of abnormality, or any abnormality...
         abnormal_CT = case_when(CTBC == 3 | CTSHFT >= 3 | CTSAH == 1 | CTIH == 1 |
                                   CTPL == 1 ~ "Abnormal",
                                 CTBC < 3 & CTSHFT < 3 & CTSAH == 2 & CTIH == 2 &
                                   CTPL == 2 ~ "Normal",
                                 TRUE ~ "No Scan") %>% as.factor(),
         CTBC = factor(CTBC, labels = ctbc_factor_levels),
         CTSHFT = factor(CTSHFT, labels = ct_midline_lvls)
  ) %>%
  mutate_at(vars(CTSAH:CTPL), factor, labels = ctscan_YN_levels) %>%
  dplyr::select(-c(CENTERID, CreatedDate:ModifiedBy))
```


```{r}
#Subsetting PT data for merging w/ prehosp data

pt_subset <- patients2 %>%
  dplyr::select(PID, PDOB, PSEX, PRACE, PWEIGHT, trauma_time, inj_mech)

#Subsetting hospitalization data for merging
hosp_subset <- prehosp2 %>% 
  dplyr::select(PID, arrival_time, arrival_date, APBILAT, APASYM, AGCSTOT, ACEI, 
                ASAO2, LRSBP, AFLUID, EDPAA, APASYM1, ACGSMOT1, ACGSTOT1, EDAAM, EDSAO2, 
                ALRSBP, EDFLUID, hypotension_ed, hypoxia_ed, pupil_ed, pupil_prehosp, pupil_ed2, 
                pupil_prehosp2, hypoxia_prehosp, hypotension_prehosp)
#DHR

# DHR Data
dhr2 <- dhr %>%
  group_by(PID) %>%
  filter(DayNo == min(DayNo)) %>%
  ungroup() %>%
  dplyr::select(PID, DHCRAN, DHSHE, DHEH, DHPHE, DHBPR, DHMECHV, DHMECHVT) %>%
  mutate_at(vars(DHCRAN, DHSHE, DHEH, DHPHE, DHBPR, DHMECHV, DHMECHVT), factor) %>%
  mutate(PID = as.character(PID),
         hematoma_evac_any = as.factor(case_when(DHSHE == 1 | DHEH == 1 | DHPHE == 1 ~ "Yes", 
                                            TRUE ~ "No")),
         craniectomy_yn = factor(case_when(DHBPR == 1 ~ "Yes",
                                           TRUE ~ "No")))



#Merging using inner join - only returning patients with matching IDS in hosp and outcomes dataset - need to know patient's outcome in order to group them
# (Alternatively, using left_join for outcomes would allow analysis of the ~ 53 patients with unknown outcome - but would that be useful??)

pt_hosp_ct <- pt_subset %>%
  inner_join(hosp_subset, by = "PID") %>% 
  inner_join(select(outcomes2, PID, outcome, followup_date), 
             by = "PID") %>%
  left_join(select(dhr2, PID, DHMECHV,DHCRAN, DHSHE, DHEH, DHPHE, DHBPR,
                   hematoma_evac_any, craniectomy_yn), by = "PID") %>%
  left_join(select(ctscan2, PID, CTBC, CTSHFT, ct_date_time, abnormal_CT, CTIH, CTSAH), 
            by = "PID") %>%   #ct - only set where inner/vs left matters-not all patients had scan
  mutate(age_at_arrival_yrs = as.numeric((arrival_date - PDOB) / 365),
         age_at_arrival_cat = as.factor(case_when(age_at_arrival_yrs < 16       ~ "0",
                                                  age_at_arrival_yrs >= 16 & 
                                                    age_at_arrival_yrs < 25     ~ "1",
                                                  age_at_arrival_yrs >= 25 &
                                                    age_at_arrival_yrs < 45     ~ "2",
                                                  age_at_arrival_yrs >= 45 &
                                                    age_at_arrival_yrs < 65     ~ "3",
                                                  age_at_arrival_yrs >= 65      ~ "4",
                                                  TRUE                          ~ NA_character_)),
         time_to_arrival_hrs = abs(as.numeric(difftime(arrival_time , trauma_time,
                                                       units = "hours"))),
         trauma_to_ct_hrs = abs(as.numeric(difftime(ct_date_time, trauma_time,
                                                    units = "hours"))),
         arrival_to_ct_hrs = abs(as.numeric(difftime(ct_date_time, arrival_time,
                                                     units = "hours"))),
         ed_gcs_tot_cat = case_when(ACGSTOT1 <= 8 & ACGSTOT1 > 5       ~ 0, #comparatively positive
                                   ACGSTOT1 <= 6 & ACGSTOT1 >= 3      ~ 1, #v suboptimal
                                   TRUE                               ~ NA_real_) %>%
           factor(labels = c("6-8", "3-5")),
         prehosp_airway_cat = as.factor(case_when(ACEI == "1"                ~ "ETI",
                                                  ACEI == "2"                ~ "LMA",
                                                  ACEI == "3"                ~ "Combitube",
                                                  ACEI == "4"                ~ "None",
                                                  TRUE                       ~ NA_character_)),
         prehosp_airway_cat = fct_relevel(prehosp_airway_cat, "ETI", "LMA", "Combitube", "None"),
         ed_airway_cat = as.factor(case_when(EDAAM == "1"            ~ "ETI",
                                             EDAAM == "2"            ~ "LMA",
                                             EDAAM == "3"            ~"Combitube",
                                             EDAAM == "4"            ~ "None",
                                             TRUE                    ~ NA_character_)),
         ed_airway_cat = fct_relevel(ed_airway_cat, "ETI", "LMA", "Combitube", "None"),
         midline_shift_cats = fct_collapse(CTSHFT, 
                                           "<= 0.5 cm" = c("No Shift", "< 0.5 cm"),
                                           "> 0.5 cm" = c("0.5-1.5 cm", "> 1.5 cm")),
         ct_yn = factor(case_when(is.na(ct_date_time) ~ "No Scan",
                                  TRUE ~ "Scan")), 
         surgery_yn = factor(case_when(DHBPR == "1" | DHSHE == "1" | DHEH == "1" | DHPHE == "1" | 
                                DHCRAN == "1" ~ "Yes",
                              TRUE ~ "No")),
         hemorrhage_any = factor(case_when(CTSAH == "Yes" | CTIH == "Yes" ~ "Yes",
                                    CTSAH == "No" & CTIH == "No" ~ "No",
                                    TRUE ~ NA_character_))) %>%
  dplyr::select(-c(arrival_date, PDOB, arrival_time, #Dropping unused variables
                   trauma_time, ct_date_time, CTIH, CTSAH)) %>%
  filter(ACGSTOT1 <= 8 & ACGSTOT1 >= 3) #Subsetting dataset to only those with ED traumaa                                                             severity of 2 (severe - GCS <=8) - and only those                                                   with valid scores (minimum total score = 3)


#NOTE: large number of NAs in pre-hospital GCS scores (254) vs 0 for ED - use ED score

tbi_clean <- pt_hosp_ct %>%
  select(-c(PID, EDAAM, ACEI, CTSHFT, followup_date, DHBPR, DHSHE, DHEH, DHPHE)) %>%
  rename(sex = "PSEX", race = "PRACE", weight = "PWEIGHT", bilat_prehosp = "APBILAT", 
         asymm_prehosp = "APASYM", gcs_total_prehosp = "AGCSTOT", sao2_prehosp = "ASAO2", 
         sbp_prehosp = "LRSBP", fluid_prehosp = "AFLUID", bilat_ed = "EDPAA", asymm_ed = "APASYM1", 
         gcs_motor_ed = "ACGSMOT1", gcs_total_ed = "ACGSTOT1", sao2_ed = "EDSAO2", sbp_ed = "ALRSBP",
         fluid_ed = "EDFLUID", basal_cist = "CTBC", craniotomy_yn = "DHCRAN", 
         mech_vent_yn = "DHMECHV") %>%
  mutate_at(vars(bilat_prehosp, asymm_prehosp, fluid_prehosp, bilat_ed, asymm_ed, fluid_ed,
                 craniotomy_yn),
            .funs = fct_recode,
            "Yes" = "1", 
            "No" = "2") %>%
  filter(age_at_arrival_yrs < 100) %>%
  mutate(outcome = fct_relevel(outcome, "Dead", "Alive"))
  
```


```{r}
#Age - continuous - significant

age_wilcox <- wilcox.test(age_at_arrival_yrs ~ outcome, data = tbi_clean)

#Age - categorical - significant

age_cat_chisq <- chisq.test(tbi_clean$age_at_arrival_cat, tbi_clean$outcome)

# Sex - nS
sex_chisq <- chisq.test(tbi_clean$sex, tbi_clean$outcome, correct = F)

# race - nS

race_fisher <- fisher.test(tbi_clean$race, tbi_clean$outcome)

# weight - NS

weight_wilcox <- wilcox.test(weight ~ outcome, data = tbi_clean)


#injury mechanism - NS
inj_fisher <- fisher.test(tbi_clean$inj_mech, tbi_clean$outcome)

#pre-hosp GCS  - sig
gcs_pre_wilcox <- wilcox.test(gcs_total_prehosp ~ outcome, data = tbi_clean)


#prehosp fluid - NS

fluid_pre_fisher <- fisher.test(tbi_clean$fluid_prehosp, tbi_clean$outcome)

#prehosp BP - NS
sbp_prehosp_ttest <- t.test(sbp_prehosp ~ outcome, data = tbi_clean)

#hypotension_prehosp NS
ht_pre_fisher <- fisher.test(tbi_clean$hypotension_prehosp, tbi_clean$outcome)

#prehosp SAO2 - NS

sao2pre_wilcox <- wilcox.test(sao2_prehosp ~ outcome, data = tbi_clean)

#prehosp hypoxia NS
hypoxia_pre_chisq <- chisq.test(tbi_clean$hypoxia_prehosp, tbi_clean$outcome, correct = F)

#Prehosp airway - NS

airway_prehosp_chisq <- chisq.test(tbi_clean$prehosp_airway_cat, tbi_clean$outcome, correct = F)

#Pre hosp APBILAT, APASYM, pupil_prehosp - NS

pupils_prehosp_chisq <- chisq.test(tbi_clean$pupil_prehosp, tbi_clean$outcome, correct = F)

pupils_prehosp2_chisq <- chisq.test(tbi_clean$pupil_prehosp2, tbi_clean$outcome, 
                                    simulate.p.value = T, correct = F)

#ED GCS - sig

gcs_ed_wilcox <- wilcox.test(gcs_total_ed ~ outcome, data = tbi_clean)

#ED GCS category - sig

gcs_cat_ed_chisq <- chisq.test(tbi_clean$ed_gcs_tot_cat, tbi_clean$outcome, correct = F)

#ED motor GCS - sig
gcs_motor_ed_wilcox <- wilcox.test(gcs_motor_ed ~ outcome, data = tbi_clean)

#ED fluid - NS

fluid_ed_chisq <- chisq.test(tbi_clean$fluid_ed, tbi_clean$outcome)

#ED BP - NS

sbp_ed_wilcox <- wilcox.test(sbp_ed ~ outcome, data = tbi_clean)

#ED SAO2 - NS

sao2_ed_wilcox <- wilcox.test(sao2_ed ~ outcome, data = tbi_clean)

#ED airway - SIG

airway_ed_chisq <- chisq.test(tbi_clean$ed_airway_cat, tbi_clean$outcome, correct = F)


#ED hypotension - NS

ht_ed_chisq <- chisq.test(tbi_clean$hypotension_ed, tbi_clean$outcome, correct = F)

#ED hypoxia - NS
hypox_ed_chisq <- chisq.test(tbi_clean$hypoxia_ed, tbi_clean$outcome, correct = F)

#ED pupils - NS
pupils_ed_chisq <- chisq.test(tbi_clean$pupil_ed, tbi_clean$outcome, correct = F)

#ED pupils - cat - NS

pupils_ed2_chisq <- chisq.test(tbi_clean$pupil_ed, tbi_clean$outcome, correct = F,
                               simulate.p.value = T)

# but - EDPAA - approaching sig
bilat_ed_chisq <- chisq.test(tbi_clean$bilat_ed, tbi_clean$outcome, correct = F)

#ED APASYM1 - ns

asymm_ed_chisq <- chisq.test(tbi_clean$asymm_ed, tbi_clean$outcome,  correct = F)

#chisq.test(factor(pt_hosp_ct$APASYM1), tbi_clean$outcome, correct = F)

#  CT y/n - sig

ct_yn_chisq <- chisq.test(tbi_clean$ct_yn, tbi_clean$outcome, correct = )

#CT - sig
abnormal_CT_chisq <- chisq.test(tbi_clean$abnormal_CT, tbi_clean$outcome, correct = F)

hemorrhage_any_chisq <- chisq.test(tbi_clean$hemorrhage_any, tbi_clean$outcome, correct = F)

#time to arrival - NS
time_to_arrival_wilcox <- wilcox.test(time_to_arrival_hrs ~ outcome, data = tbi_clean)

# trauma time to CT - sig

trauma_to_ct_wilcox <- wilcox.test(trauma_to_ct_hrs ~ outcome, data = tbi_clean)

#Midline shift - p  0.063
 #chisq.test(pt_hosp_ct$CTSHFT, tbi_clean$outcome, correct = F)

# more importantly: significant when comparing >= 5 mm shift to < 5 mm (including none)

midline_chisq <- chisq.test(tbi_clean$midline_shift_cats, tbi_clean$outcome, correct = FALSE)

#Basal cisterns - p < 0.001

basal_cist_chisq <- chisq.test(tbi_clean$basal_cist, tbi_clean$outcome, correct = F)


##### DHR - surgeries on day one only - surgery_yn

#any surgery yn -- obviously sig

surgery_any_chisq <- chisq.test(tbi_clean$surgery_yn, tbi_clean$outcome, correct = F)

#craniectomy yn - not sig 

craniectomy_chisq <- chisq.test(tbi_clean$craniectomy_yn, tbi_clean$outcome, correct = F)

#craniotomy yn - sig

craniotomy_chisq <- chisq.test(tbi_clean$craniotomy_yn, tbi_clean$outcome, correct = F)

#hematoma yn - sig

hematoma_chisq <- chisq.test(tbi_clean$hematoma_evac_any, tbi_clean$outcome, correct = F)
```



```{r}
#Creating Summary Statistics Table
test_list <- list(age_wilcox, age_cat_chisq, sex_chisq, race_fisher, weight_wilcox, inj_fisher, 
                  
                  gcs_pre_wilcox, airway_prehosp_chisq, sao2pre_wilcox, hypoxia_pre_chisq, 
                  sbp_prehosp_ttest, ht_pre_fisher, fluid_pre_fisher, pupils_prehosp_chisq, 
                  
                  time_to_arrival_wilcox, gcs_ed_wilcox, gcs_cat_ed_chisq, gcs_motor_ed_wilcox, 
                  airway_ed_chisq, sao2_ed_wilcox, hypox_ed_chisq, sbp_ed_wilcox, ht_ed_chisq, 
                  fluid_ed_chisq, pupils_ed_chisq, bilat_ed_chisq, asymm_ed_chisq, 
                  
                  ct_yn_chisq, trauma_to_ct_wilcox, abnormal_CT_chisq, midline_chisq, 
                  basal_cist_chisq, hemorrhage_any_chisq,
                  
                  surgery_any_chisq, craniotomy_chisq, craniectomy_chisq, hematoma_chisq)

teststat_values <- lapply(test_list, function(x)
  {
  if(!is.null(x$statistic)){
    test_stat <- round(x$statistic, 3)
  }
  else {
    test_stat <- " "
  }
  
  c(test_stat, scaff_pvnot(x$p.value))
  })

summary_table1 <- 
  list(#PT characteristics
    "Age (Years)" =
      list("Mean &plusmn; SD" = ~ mean_sd(.data$age_at_arrival_yrs, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$age_at_arrival_yrs, na_rm = T, 
                                         show_n = "never")),
    "Age (Years) - n(%)" = 
      list("< 16" = ~ n_perc0(.data$age_at_arrival_cat == "0", na_rm = T),
           "16 - 24" = ~ n_perc0(.data$age_at_arrival_cat == "1", na_rm = T), 
           "25 - 44" = ~ n_perc0(.data$age_at_arrival_cat == "2", na_rm = T),
           "45-64" = ~ n_perc0(.data$age_at_arrival_cat == "3", na_rm = T),
           "65+" = ~ n_perc0(.data$age_at_arrival_cat == "4", na_rm = T)),
    "Sex - n(%)" =
      list("Male" = ~ n_perc0(.data$sex == "1", na_rm = T),
           "Female" = ~ n_perc0(.data$sex == "2", na_rm = T)),
    "Patient Race - n(%)" =
      list("Black / African" = ~ n_perc0(.data$race == "2", na_rm = T),
           "Asian or Pacific Islander" = ~ n_perc0(.data$race == "4", na_rm = T)),
    "Weight (kg)" =
      list("Mean &plusmn; SD" = ~ mean_sd(.data$weight, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$weight, na_rm = T, 
                                         show_n = "never")),
    "Mechanism of Injury - n(%)" =
      list("MVA/Bike" = ~ n_perc0(.data$inj_mech == "MVA/Bike", na_rm = T),
           "Assault/BFT" = ~ n_perc0(.data$inj_mech == "Assault/BFT", na_rm = T),
           "Fall" = ~ n_perc0(.data$inj_mech == "Fall", na_rm = T),
           "All Other" = ~ n_perc0(.data$inj_mech == "All Other", na_rm = T))
         )

#Pre-hospitalization factors
summary_table2 <-
  list(
    "GCS Total Score" =
      list("Mean &plusmn; SD" = ~ mean_sd(.data$gcs_total_prehosp, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$gcs_total_prehosp, na_rm = T, 
                                         show_n = "never")),
    "Advanced Airway Management (Y/N)- n(%)" = 
      list("ETI" = ~ n_perc0(.data$prehosp_airway_cat == "ETI", na_rm = T),
           "LMA" = ~ n_perc0(.data$prehosp_airway_cat == "LMA", na_rm = T), 
           "Combitube" = ~ n_perc0(.data$prehosp_airway_cat == "Combitube", na_rm = T), 
           "None" = ~ n_perc0(.data$prehosp_airway_cat == "None", na_rm = T)),
    "Lowest Recorded Oxygen Saturation (SaO2) %age" =
      list("Mean &plusmn; SD" = ~ mean_sd(.data$sao2_prehosp, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$sao2_prehosp, na_rm = T, 
                                         show_n = "never")),
    "Pre-Hospital Hypoxia - n(%)" =
      list("Yes" = ~ n_perc0(.data$hypoxia_prehosp == "Yes", na_rm = T),
           "No"  = ~ n_perc0(.data$hypoxia_prehosp == "No", na_rm = T)),
    "Lowest Recorded Systolic BP (mmHG)" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$sbp_prehosp, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~median_iqr(.data$sbp_prehosp, na_rm = T, 
                                        show_n = "never")),
    "Pre-Hospital Hypotension - n(%)" =
      list("Yes" = ~ n_perc0(.data$hypotension_prehosp == "Yes", na_rm = T),
           "No"  = ~ n_perc0(.data$hypotension_prehosp == "No", na_rm = T)),
    "Pre-Hospital IV (Y/N) - n(%)" = 
      list("Yes" = ~ n_perc0(.data$fluid_prehosp == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$fluid_prehosp == "No", na_rm = T)),
    "Pre-Hospital Pupil Abnormalities (Y/N) - n(%)" =
      list("Yes" = ~ n_perc0(.data$pupil_prehosp == "1", na_rm = T),
           "No"  = ~ n_perc0(.data$pupil_prehosp == "0", na_rm = T))
  )

#ED factors

summary_table3 <-
  list(
    "Time to Arrival at ED (Hours)" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$time_to_arrival_hrs, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$time_to_arrival_hrs, na_rm = T, 
                                         show_n = "never")),
    "GCS Total Score" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$gcs_total_ed, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$gcs_total_ed, na_rm = T, 
                                         show_n = "never")),
    "GCS Total Score - n(%)" = 
      list("3-5" = ~ n_perc0(.data$ed_gcs_tot_cat == "3-5", na_rm = T),
           "6-8" = ~ n_perc0(.data$ed_gcs_tot_cat == "6-8", na_rm = T)),
    "GCS Motor Score" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$gcs_motor_ed, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$gcs_motor_ed, na_rm = T, 
                                         show_n = "never")),
    "Advanced Airway Management - n(%)" = 
      list("ETI" = ~ n_perc0(.data$ed_airway_cat == "ETI", na_rm = T),
           "LMA" = ~ n_perc0(.data$ed_airway_cat == "LMA", na_rm = T), 
           "Combitube" = ~ n_perc0(.data$ed_airway_cat == "Combitube", na_rm = T), 
           "None" = ~ n_perc0(.data$ed_airway_cat == "None", na_rm = T)),
    "Lowest Recorded Oxygen Saturation (SaO2) %age" =
      list("Mean &plusmn; SD" = ~ mean_sd(.data$sao2_ed, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$sao2_ed, na_rm = T, 
                                         show_n = "never")),
    "ED Hypoxia - n(%)" =
      list("Yes" = ~ n_perc0(.data$hypoxia_ed == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$hypoxia_ed == "No", na_rm = T)),
    "Lowest Recorded Systolic BP (mmHG)" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$sbp_ed, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~median_iqr(.data$sbp_ed, na_rm = T, 
                                        show_n = "never")),
    "ED Hypotension - n(%)" =
      list("Yes" = ~ n_perc0(.data$hypotension_ed == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$hypotension_ed == "No", na_rm = T)),
    "ED IV (Y/N) - n(%)" = 
      list("Yes" = ~ n_perc0(.data$fluid_ed == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$fluid_ed == "No", na_rm = T)),
    "Abnormal Pupils in ED - n(%)" = 
      list("Yes" = ~ n_perc0(.data$pupil_ed == "1", na_rm = T),
           "No" =  ~ n_perc0(.data$pupil_ed == "0", na_rm = T)),
    "ED Bilateral Fixed & Dilated Pupils (Y/N) - n(%)" =
      list("Yes" = ~ n_perc0(.data$bilat_ed == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$bilat_ed == "No", na_rm = T)),
    "ED Pupil Asymmetry > 1mm - n(%)" =
      list("Yes" = ~ n_perc0(.data$asymm_ed == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$asymm_ed == "No", na_rm = T)),
    "CT Scan Performed (Y/N) - n(%)" =
      list("Yes" = ~ n_perc0(.data$ct_yn == "Scan", na_rm = T),
           "No" = ~ n_perc0(.data$ct_yn == "No Scan", na_rm = T)),
    "Time (Injury to CT Scan) (Hours)" = 
      list("Mean &plusmn; SD" = ~ mean_sd(.data$trauma_to_ct_hrs, na_rm = T, 
                                          show_n = "never"),
           "Median (IQR)" = ~ median_iqr(.data$trauma_to_ct_hrs, na_rm = T, 
                                         show_n = "never")),
    "Abnormal CT Scan (Y/N) - n(%)" =
      list("Yes" = ~ n_perc0(.data$abnormal_CT == "Abnormal", na_rm = T),
           "No" = ~ n_perc0(.data$abnormal_CT == "Normal", na_rm = T)),
    "Midline Shift on CT Scan - n(%)" =
      list("<= 0.5 cm" = ~ n_perc0(.data$midline_shift_cats == "<= 0.5 cm", na_rm = T),
           "> 0.5 cm" = ~ n_perc0(.data$midline_shift_cats == "> 0.5 cm", na_rm = T)),
    "Basal Cistern Status on CT Scan - n(%)" =
      list("Open" = ~ n_perc0(.data$basal_cist == "Open", na_rm = T),
           "Partially Open" = ~ n_perc0(.data$basal_cist == "Partially Open", na_rm = T),
           "Closed" = ~ n_perc0(.data$basal_cist == "Closed", na_rm = T)),
    "Hemorrhage (Intracerebral or Subarachnoid) - n(%)" =
      list("Yes" = ~ n_perc0(.data$hemorrhage_any == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$hemorrhage_any == "No", na_rm = T))
  )


#DHR / surgery table

summary_table4 <-
  list(
    "Any Neurological Surgery Performed" =
      list("Yes" = ~ n_perc0(.data$surgery_yn == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$surgery_yn == "No", na_rm = T)),
    "Craniotomy - n(%)" =
      list("Yes" = ~ n_perc0(.data$craniotomy_yn == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$craniotomy_yn == "No", na_rm = T)),
    "Hematoma Evacuation - n(%)" =
      list("Yes" = ~ n_perc0(.data$hematoma_evac_any == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$hematoma_evac_any == "No", na_rm = T)),
    "Decompressive Craniectomy - n(%)" =
      list("Yes" = ~ n_perc0(.data$craniectomy_yn == "Yes", na_rm = T),
           "No" = ~ n_perc0(.data$craniectomy_yn == "No Open", na_rm = T))
  )
```



```{r, results = 'asis'}

patient_table <- cbind(summary_table(tbi_clean, summary_table1),
      summary_table(group_by(tbi_clean, outcome), summary_table1))

pcol_1 <- rep("", times = nrow(patient_table))

rep_rows <- c(1, 3, 8, 10, 12, 14)
pcol_1[rep_rows] <- as.character(sapply(seq(from = 1, length.out = 
                                              length(rep_rows)), 
                                        function(x)
                                          {
                                          teststat_values[[x]][2]
                                          } )) 

patient_table2 <- cbind(patient_table, pcol_1)


prehosp_table <- cbind(summary_table(tbi_clean, summary_table2),
      summary_table(group_by(tbi_clean, outcome), summary_table2))

pcol_2 <- rep("", times = nrow(prehosp_table))
rep_rows <- c(1, 3, 7, 9, 11, 13, 15, 17)
pcol_2[rep_rows] <- as.character(sapply(seq(from = 7, length.out = 
                                              length(rep_rows)), 
                                        function(x)
                                          {
                                          teststat_values[[x]][2]
                                          } ))
prehosp_table2 <- cbind(prehosp_table, pcol_2)

ed_table <- cbind(summary_table(tbi_clean, summary_table3),
      summary_table(group_by(tbi_clean, outcome), summary_table3))

pcol_3 <- rep("", times = nrow(ed_table))
rep_rows <- c(1, 3, 5, 7, 9, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 40)
pcol_3[rep_rows] <- as.character(sapply(seq(from = 15, length.out = 
                                              length(rep_rows)), 
                                        function(x)
                                          {
                                          teststat_values[[x]][2]
                                          } ))

ed_table2 <- cbind(ed_table, pcol_3)

#Colnames
cols <- c(paste0("Total (N = ", nrow(pt_hosp_ct), ")"), 
           paste0("Dead (n = ", 
                  nrow(pt_hosp_ct[tbi_clean$outcome == "Dead",]), ")"),
          paste0("Alive at F/up (n = ", 
                  nrow(pt_hosp_ct[tbi_clean$outcome == "Alive",]), ")"),
           "P-value")


dhr_table1 <- cbind(summary_table(tbi_clean, summary_table4),
      summary_table(group_by(tbi_clean, outcome), summary_table4))

pcol_4 <- rep("", times = nrow(dhr_table1))
rep_rows <- c(1, 3, 5, 7)
pcol_4[rep_rows] <- as.character(sapply(seq(from = 33, length.out = 
                                              length(rep_rows)), 
                                        function(x)
                                          {
                                          teststat_values[[x]][2]
                                          } ))
dhr_table2 <- cbind(dhr_table1, pcol_4)

colnames(patient_table2) <- cols
colnames(prehosp_table2) <- cols
colnames(ed_table2) <- cols
colnames(dhr_table2) <- cols
```


*Table 1.* Patient characteristics by outcome.
```{r, results = "asis"}
print(patient_table2)
```

*Table 2.* Pre-hospitalization factors by patient outcome.
```{r, results = "asis"}
print(prehosp_table2)
```

*Table 3.* ED factors by patient outcome.
```{r, results = "asis"}
print(ed_table2)
```

*Table 4.* Surgical procedures by outcome.

```{r, results = "asis"}
print(dhr_table2)
```

